# Generated by Django 4.2.6 on 2023-11-02 05:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import website.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("isbn", models.IntegerField(default=0)),
                ("issue", models.BooleanField(default=False)),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                ("ret_date", models.DateField(default=website.models.get_expiry)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="NAME", max_length=20)),
                ("usn", models.IntegerField()),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=20)),
                ("fine", models.IntegerField(default=0)),
                ("issue", models.BooleanField(default=False)),
                (
                    "issued",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.book",
                    ),
                ),
            ],
        ),
    ]
