# Generated by Django 4.2.6 on 2024-02-02 13:19

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "user_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "librarian"),
                            (2, "staff"),
                            (3, "student"),
                            (4, "library_staff"),
                        ]
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("phone", models.CharField(max_length=10)),
                ("fine", models.IntegerField(default=0)),
                (
                    "id_number",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "permissions": [("librarian", "Librarian")],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("name", models.CharField(max_length=200)),
                ("isbn", models.IntegerField(default=None)),
                ("publisher", models.CharField(default=None, max_length=400)),
                (
                    "access_code",
                    models.IntegerField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        choices=[("UG", "Ug"), ("PG", "Pg")],
                        default="UG",
                        max_length=10,
                    ),
                ),
                ("edition", models.IntegerField(default=None)),
                ("author", models.CharField(default=None, max_length=200)),
                ("status", models.CharField(default="available", max_length=200)),
                (
                    "category",
                    models.CharField(blank=True, default=None, max_length=200),
                ),
                ("issue_date", models.DateField(blank=True, default=None, null=True)),
                ("ret_date", models.DateField(blank=True, default=None, null=True)),
                ("reference", models.BooleanField(default=False)),
                (
                    "purchase_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                ("cost", models.IntegerField(blank=True, default=None, null=True)),
                ("pub_year", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "issue_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("only_view_book", "Only View Book"),
                    ("edit_only_book", "Edit Only Book"),
                    ("add_only_book", "Add Only Book"),
                ],
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="files/")),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("date_uploaded", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("only_view", "Only View"),
                    ("add", "Add"),
                    ("delete", "Delete"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Holidays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Magazine",
            fields=[
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(blank=True, default=None, max_length=200),
                ),
                ("author", models.CharField(default=None, max_length=200)),
                ("isbn", models.IntegerField(default=None)),
                ("edition", models.CharField(default=None, max_length=200)),
                (
                    "publisher",
                    models.CharField(
                        blank=True, default=None, max_length=400, null=True
                    ),
                ),
                (
                    "access_code",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("cost", models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                "permissions": [
                    ("only_view_magazine", "Only View Magazine"),
                    ("edit_only_magazine", "Edit Only Magazine"),
                    ("add_only_magazine", "Add Only Magazine"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TransactionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(blank=True, default=0, null=True)),
                ("transaction_type", models.CharField(max_length=200)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
                (
                    "file_notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.file",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalUsers",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "user_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "librarian"),
                            (2, "staff"),
                            (3, "student"),
                            (4, "library_staff"),
                        ]
                    ),
                ),
                ("photo", models.TextField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("phone", models.CharField(max_length=10)),
                ("fine", models.IntegerField(default=0)),
                ("id_number", models.CharField(db_index=True, max_length=200)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical users",
                "verbose_name_plural": "historical userss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalNotification",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("date_uploaded", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "file_notification",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="website.file",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical notification",
                "verbose_name_plural": "historical notifications",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFile",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("file", models.TextField(blank=True, max_length=100, null=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "date_uploaded",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical file",
                "verbose_name_plural": "historical files",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBook",
            fields=[
                ("name", models.CharField(max_length=200)),
                ("isbn", models.IntegerField(default=None)),
                ("publisher", models.CharField(default=None, max_length=400)),
                ("access_code", models.IntegerField(db_index=True, default=None)),
                (
                    "course",
                    models.CharField(
                        choices=[("UG", "Ug"), ("PG", "Pg")],
                        default="UG",
                        max_length=10,
                    ),
                ),
                ("edition", models.IntegerField(default=None)),
                ("author", models.CharField(default=None, max_length=200)),
                ("status", models.CharField(default="available", max_length=200)),
                (
                    "category",
                    models.CharField(blank=True, default=None, max_length=200),
                ),
                ("issue_date", models.DateField(blank=True, default=None, null=True)),
                ("ret_date", models.DateField(blank=True, default=None, null=True)),
                ("reference", models.BooleanField(default=False)),
                (
                    "purchase_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                ("cost", models.IntegerField(blank=True, default=None, null=True)),
                ("pub_year", models.IntegerField(blank=True, default=None, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue_to",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical book",
                "verbose_name_plural": "historical books",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Book_Copies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_copies", models.IntegerField(default=0)),
                ("issued_copies", models.IntegerField(default=0)),
                ("available_copies", models.IntegerField(default=0)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copies",
                        to="website.book",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="users",
            name="issued_book",
            field=models.ManyToManyField(
                blank=True, related_name="users_books", to="website.book"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
