# Generated by Django 4.2.6 on 2023-10-28 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="isbn",
        ),
        migrations.RemoveField(
            model_name="user",
            name="fine",
        ),
    ]
