# Generated by Django 4.2.6 on 2023-11-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="issued_book",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="users_books", to="website.book"
            ),
        ),
    ]
