# Generated by Django 4.2.6 on 2023-11-18 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_alter_users_issued_book"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="users",
            managers=[],
        ),
    ]
