# Generated by Django 4.2.6 on 2023-10-29 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_remove_book_isbn_remove_user_fine"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="book",
            name="issue",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="fine",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=20),
        ),
    ]
