# Generated by Django 4.2.6 on 2023-11-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_remove_student_issue"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="issue",
            field=models.BooleanField(default=False),
        ),
    ]
