# Generated by Django 4.2.6 on 2023-11-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_alter_book_category_alter_magazine_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magazine",
            name="issue_to",
            field=models.TextField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name="reference",
            name="issue_to",
            field=models.TextField(default=0, max_length=20),
        ),
    ]
