# Generated by Django 4.2.10 on 2024-03-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_remove_book_volume_remove_historicalbook_volume_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.CharField(blank=True, default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.CharField(default=None, max_length=4000),
        ),
        migrations.AlterField(
            model_name="historicalbook",
            name="category",
            field=models.CharField(blank=True, default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name="historicalbook",
            name="name",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="historicalbook",
            name="publisher",
            field=models.CharField(default=None, max_length=4000),
        ),
    ]
