# Generated by Django 4.2.6 on 2023-10-29 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_book_isbn_book_issue_user_email_user_fine_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="issued",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.book",
            ),
        ),
    ]
