# Generated by Django 4.2.6 on 2023-11-02 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_student_issue"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="issue_to",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.student",
            ),
        ),
    ]
