# Generated by Django 4.2.6 on 2023-11-19 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_alter_users_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": [
                    ("only_view_book", "Only View Book"),
                    ("edit_only_book", "Edit Only Book"),
                    ("add_only_book", "Add Only Book"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="file",
            options={
                "permissions": [
                    ("only_view", "Only View"),
                    ("add", "Add"),
                    ("delete", "Delete"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="magazine",
            options={
                "permissions": [
                    ("only_view_magazine", "Only View Magazine"),
                    ("edit_only_magazine", "Edit Only Magazine"),
                    ("add_only_magazine", "Add Only Magazine"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="users",
            options={"permissions": [("librarian", "Librarian")]},
        ),
    ]
