# Generated by Django 4.2.10 on 2024-03-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_alter_book_category_alter_book_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="owner",
        ),
        migrations.AddField(
            model_name="message",
            name="subject",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
