# Generated by Django 4.2.6 on 2024-02-02 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_historicalusers_historicalnotification_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionlog",
            name="book",
        ),
    ]
