# Generated by Django 4.2.6 on 2023-11-09 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_issue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.reference",
            ),
        ),
    ]
