# Generated by Django 4.2.6 on 2023-11-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_alter_book_options_alter_file_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="user_num",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
