# Generated by Django 4.2.10 on 2024-03-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_remove_message_owner_message_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
