# Generated by Django 4.2.6 on 2023-10-30 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_rename_user_stu_book_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Stu",
            new_name="Student",
        ),
    ]
