# Generated by Django 4.2.6 on 2023-11-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_file_user_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="magazine",
            name="copies",
        ),
        migrations.RemoveField(
            model_name="magazine",
            name="issue_date",
        ),
        migrations.RemoveField(
            model_name="magazine",
            name="ret_date",
        ),
        migrations.AddField(
            model_name="magazine",
            name="edition",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
