# Generated by Django 4.2.6 on 2023-11-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_remove_magazine_copies_remove_magazine_issue_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="date_uploaded",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
