# Generated by Django 4.2.6 on 2023-10-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_rename_stu_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="user",
        ),
        migrations.AddField(
            model_name="student",
            name="usn",
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
