# Generated by Django 4.2.6 on 2023-11-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_issue_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="issue_to",
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name="magazine",
            name="issue_to",
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name="reference",
            name="issue_to",
            field=models.CharField(default=0, max_length=200),
        ),
    ]
