# Generated by Django 4.2.6 on 2023-11-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_remove_book_issue_to_alter_student_issued"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(default="EWIT", max_length=200),
        ),
        migrations.AlterField(
            model_name="student",
            name="usn",
            field=models.CharField(max_length=7),
        ),
    ]
