# Generated by Django 4.2.6 on 2023-11-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_book_author_alter_student_usn"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="usn",
            field=models.CharField(default=20, max_length=20),
        ),
    ]
