# Generated by Django 4.2.6 on 2023-10-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_remove_book_user_student_usn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="usn",
            field=models.IntegerField(default=0),
        ),
    ]
