# Generated by Django 4.2.10 on 2024-03-25 05:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_historicalnotification_user_notification_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalnotification",
            name="file_notification",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="file_notification",
        ),
    ]
