# Generated by Django 4.2.6 on 2023-11-03 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_book_usn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="usn",
        ),
    ]
