# Generated by Django 4.2.6 on 2023-11-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_alter_student_issued"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="usn",
            field=models.IntegerField(),
        ),
    ]
