# Generated by Django 4.2.6 on 2023-11-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_alter_book_issue_to_alter_magazine_issue_to_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="magazine",
            name="issue_to",
        ),
        migrations.AlterField(
            model_name="student",
            name="issued_Book",
            field=models.ManyToManyField(blank=True, to="website.book"),
        ),
        migrations.AlterField(
            model_name="student",
            name="issued_Reference",
            field=models.ManyToManyField(blank=True, to="website.reference"),
        ),
    ]
