# Generated by Django 4.2.6 on 2023-11-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_remove_book_usn"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="usn",
            field=models.CharField(default=0, max_length=20),
        ),
    ]
