# Generated by Django 4.2.6 on 2023-11-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_student_name_alter_student_email_alter_student_usn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(default="NAME", max_length=20),
        ),
    ]
