# Generated by Django 4.2.6 on 2023-11-04 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_book_usn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="issue_date",
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
