# Generated by Django 4.2.6 on 2023-11-09 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_remove_magazine_issue_to_alter_student_issued_book_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="issued",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_issues",
                to="website.issue",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="issued",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_issues",
                to="website.issue",
            ),
        ),
    ]
