# Generated by Django 4.2.6 on 2023-11-01 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_alter_student_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="issued",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.book",
            ),
        ),
    ]
