# Generated by Django 4.2.6 on 2023-11-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_staff_issued_student_issued"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="issue_to",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="reference",
            name="issue_to",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
