# Generated by Django 4.2.6 on 2023-11-10 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0012_alter_book_issue_to_alter_reference_issue_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="issued",
        ),
        migrations.RemoveField(
            model_name="student",
            name="issued",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="issued_book",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="issued_reference",
        ),
        migrations.RemoveField(
            model_name="student",
            name="issued_Book",
        ),
        migrations.RemoveField(
            model_name="student",
            name="issued_Reference",
        ),
        migrations.AddField(
            model_name="staff",
            name="issued_book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_books",
                to="website.book",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="issued_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_references",
                to="website.reference",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="issued_Book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_books",
                to="website.book",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="issued_Reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_references",
                to="website.reference",
            ),
        ),
    ]
