# Generated by Django 4.2.6 on 2023-11-10 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_alter_student_issued_book_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="issued_Book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_books",
                to="website.book",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="issued_Reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_references",
                to="website.reference",
            ),
        ),
    ]
