# Generated by Django 4.2.6 on 2023-11-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0015_alter_student_issued_book_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="return",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="return",
            name="book",
        ),
        migrations.RemoveField(
            model_name="return",
            name="staff",
        ),
        migrations.RemoveField(
            model_name="return",
            name="student",
        ),
        migrations.AlterField(
            model_name="reference",
            name="issue_to",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name="Issue",
        ),
        migrations.DeleteModel(
            name="Return",
        ),
    ]
