# Generated by Django 4.2.6 on 2023-11-11 05:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0017_alter_reference_author_alter_reference_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="issued_reference",
        ),
        migrations.RemoveField(
            model_name="student",
            name="issued_Reference",
        ),
    ]
